a = float(input("Cost of one computer: "))
b = float(input("Number of computers: "))
d = float(input("Number of tables: "))
e = float(input("Cost of one table: "))
g = float(input("Number of chairs: "))
h = float(input("Cost of one chair: "))
i = float(input("Number of hours worked: "))
j = input("Wages per hour: ")
c = int(a)*int(b)
r = float(int(d)*int(e)) + (int(g)*int(h))
v = int(i)*int(j)
print("Total Lab cost: ",int(c+r+v))
